# Generated by Django 5.2.8 on 2025-11-30 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('manager', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gerente/Responsável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome do Tipo')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código (ex: temp, hum)')),
                ('unit', models.CharField(max_length=20, verbose_name='Unidade Padrão')),
                ('icon', models.CharField(default='bi-activity', max_length=50, verbose_name='Ícone Bootstrap')),
                ('min_value_default', models.FloatField(default=0, verbose_name='Mínimo Padrão')),
                ('max_value_default', models.FloatField(default=100, verbose_name='Máximo Padrão')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Sensor',
                'verbose_name_plural': 'Tipos de Sensor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='sensors.region', verbose_name='Região')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('connection_type', models.CharField(choices=[('bluetooth', 'Bluetooth'), ('wifi', 'Wi-Fi'), ('usb', 'USB'), ('lora', 'LoRaWAN'), ('ethernet', 'Ethernet')], default='wifi', max_length=20, verbose_name='Conexão')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='Endereço MAC')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('battery_level', models.IntegerField(default=100, verbose_name='Nível da Bateria')),
                ('value', models.FloatField(default=0, verbose_name='Valor')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade')),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Atenção'), ('alert', 'Alerta'), ('disconnected', 'Desconectado'), ('error', 'Erro')], default='normal', max_length=20, verbose_name='Status')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Atualização')),
                ('min_value', models.FloatField(default=0, verbose_name='Valor Mínimo')),
                ('max_value', models.FloatField(default=100, verbose_name='Valor Máximo')),
                ('warning_min', models.FloatField(default=20, verbose_name='Mínimo para Atenção')),
                ('warning_max', models.FloatField(default=80, verbose_name='Máximo para Atenção')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensors.location', verbose_name='Localização')),
                ('sensor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensors.sensortype', verbose_name='Tipo de Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='Mensagem')),
                ('severity', models.CharField(choices=[('critical', 'Crítico'), ('warning', 'Aviso'), ('info', 'Informação')], default='info', max_length=20, verbose_name='Severidade')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Ação')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalhes')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
